version: '3.8'

services:
  watcher:
    build: .
    env_file: .env
    command: ["sh", "-c", "watcher"]
    environment:
      - UPDATER_HOST=updater
    depends_on:
      updater:
        condition: service_healthy
    networks:
      - igdb-autocomplete

  updater:
    build: .
    env_file: .env
    command: ["sh", "-c", "updater"]
    environment:
      - GIN_MODE=release
    networks:
      - igdb-autocomplete
    healthcheck:
      test: "wget --no-verbose --tries=1 http://127.0.0.1:${UPDATER_PORT}/heartbeat || exit 1"
      interval: 2s
      timeout: 1s
      retries: 3      
    
networks:
  igdb-autocomplete:
    driver: bridge