# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  go: circleci/go@1.11.0

jobs:
  build:
    executor:
      name: go/default
      tag: 1.21.1
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Build application
          command: make ci

  test:
    executor:
      name: go/default
      tag: 1.21.1
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
