name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.0'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build application
        run: make ci

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.0'
          cache: true

      - name: Run tests
        run: go test -v -covermode=atomic -failfast -race ./...
