name: CI

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: .ruby-version
            bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --no-color

  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Prepare test database
        run: bin/rails db:test:prepare

      - name: Run RSpec
        run: bundle exec rspec
